Timely v2 changes
joinditto/react-timely-plugin pull request #1
Opened 2024-09-25 11:45 UTC by sachinmjadhav

* Remove close button
* Update packages

2024-09-25 19:29 UTC, arifraveendran reviewed
rest looks good

2024-09-25 19:29 UTC, arifraveendran commented on src/components/TimelyModal.tsx
> +  children: React.ReactNode
already extending propswithchildren right ?

2024-10-08 08:59 UTC, arifraveendran requested changes

2024-10-08 08:59 UTC, arifraveendran commented on example/src/App.tsx
> +      window.location.href = event.data.action
isn't it better to open these links in a new tab ?

2024-10-08 09:07 UTC, sachinmjadhav commented on example/src/App.tsx
> +      window.location.href = event.data.action
Ok, should we not close the modal on link click?

2024-10-08 09:18 UTC, arifraveendran commented on example/src/App.tsx
> +      window.location.href = event.data.action
better not close it in case the user wants to check the all the links.

2024-10-10 12:09 UTC, arifraveendran approved these changes

2024-10-10 12:10 UTC, merged